### PR TITLE
zedwallet/icon

### PR DESCRIPTION
**Pull request by bakedminds**
changed the icons and fixed zedwallet error issue

### CODE REVIEW

**Comment by bakedminds** [comment]
removed TRTL ICON and added OWL ICON. also changed zedwallet to wallet in src/Cmakelists.txt

**Comment by brandonlehmann** [comment]
I’d prefer to keep the zedwallet name — what’s the harm ?

**Comment by brandonlehmann** [comment]
Also... why does this show such massive changes to the whole files ?

**Comment by ZedPea** [comment]
This shouldn't work I don't think - `set_property(TARGET Wallet PROPERTY OUTPUT_NAME "wallet")`

This is changing the bit it's linking together from zedwallet to Wallet - but it's defined up above as zedwallet so this shouldn't find anything. You want to change the bit in quotes instead to something else I think.

**Comment by brandonlehmann** [comment]
Correct.

**Comment by bakedminds** [comment]
when i compiled everything i was getting a linking error when - set_property(Target Wallet was  - set_property(Target zedWallet. im still learning how to do this stuff and asked Zpalmtree for some help.  he pointed me in the right direction and i just kept figuring it out as i went. when i compiled what you see my changes the output was still zedwallet.  i just changed the code to - set_property(Target zedwallet Property OUTPUT_NAME "zedwallet" rebuilt and recompiled and seems to be working fine. sorry for all the stupid commits im new to this github stuff and trying to work my way around it

**Comment by ZedPea** [comment]
The cmake looks fine now.

**Comment by bakedminds** [comment]
thanks. taking baby steps.  ill try to pay attention more when doing commits and changes

**Pull request merged**
